# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-08 07:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_auto_20170207_1133'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='answer_wegiht',
            field=models.BigIntegerField(default=1),
        ),
    ]
