# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-08 11:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_faq_answer_wegiht'),
    ]

    operations = [
        migrations.RenameField(
            model_name='faq',
            old_name='question_keywork',
            new_name='question_keyword',
        ),
        migrations.RenameField(
            model_name='faq',
            old_name='answer_wegiht',
            new_name='teacher_wegiht',
        ),
        migrations.AddField(
            model_name='faq',
            name='student_evaluation',
            field=models.DecimalField(decimal_places=2, default=50.0, max_digits=5),
        ),
    ]
