# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-21 02:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_auto_20170208_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='student_evaluation',
            field=models.FloatField(default=50.0, max_length=10),
        ),
    ]
