# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-28 02:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0008_usersession'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersession',
            name='userid',
            field=models.BigIntegerField(default=1),
        ),
    ]
