# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-28 02:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0009_usersession_userid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersession',
            name='time',
            field=models.CharField(max_length=50),
        ),
    ]
