# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-28 03:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0010_auto_20170328_0237'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersession',
            name='user_evalution',
            field=models.BigIntegerField(default=3),
        ),
    ]
