# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-28 03:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0011_usersession_user_evalution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersession',
            name='user_evalution',
            field=models.FloatField(),
        ),
    ]
