# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-14 08:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0012_auto_20170328_0325'),
    ]

    operations = [
        migrations.CreateModel(
            name='Knowledge',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('question_content', models.TextField()),
                ('answer_content', models.TextField()),
            ],
        ),
    ]
