# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-24 10:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0013_knowledge'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='baidu_answer',
            field=models.TextField(default=''),
        ),
    ]
